### PR TITLE
Added week 2 submission of Scarne's Dice Game

### PR DESCRIPTION
**Pull request by ashru**

### CODE REVIEW

**Comment by OrkoHunter** [comment]
It would be good if you could submit the actual code instead of the `.rar` file.

**Comment by ashru** [comment]
Folder with sources added. Please merge @AvijitGhosh82

**Comment by evijit** [comment]
Looks good. Merged and closed.

**Comment by pranitbauva1997** [comment]
Please take care to not submit PR's from the master branch. It makes the commit tree look horrible once you pull recent changes which further makes submitting the next PR even more horrible

**Pull request merged**
